server.port=8080
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-registry:8761/eureka/}
eureka.instance.prefer-ip-address=true

# Direct Container Route Mappings
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=student-service
spring.cloud.gateway.routes[1].uri=http://student-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/students/**

spring.cloud.gateway.routes[2].id=course-service
spring.cloud.gateway.routes[2].uri=http://course-service:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/courses/**

spring.cloud.gateway.routes[3].id=marks-service
spring.cloud.gateway.routes[3].uri=http://marks-service:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/marks/**

spring.cloud.gateway.routes[4].id=attendance-service
spring.cloud.gateway.routes[4].uri=http://attendance-service:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/attendance/**

spring.cloud.gateway.routes[5].id=assignment-service
spring.cloud.gateway.routes[5].uri=http://assignment-service:8086
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/assignments/**

spring.cloud.gateway.routes[6].id=notice-service
spring.cloud.gateway.routes[6].uri=http://notice-service:8087
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/notices/**

spring.cloud.gateway.routes[7].id=placement-service
spring.cloud.gateway.routes[7].uri=http://placement-service:8088
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/placement/**

spring.cloud.gateway.routes[8].id=feedback-service
spring.cloud.gateway.routes[8].uri=http://feedback-service:8089
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/feedback/**
